### ISSUE TITLE
Look into Webmin administration tool

### ISSUE THREAD

**Issue by teusink** [teusink/Home-Security-by-Pi#18]
Look into Webmin administration tool

Sources:
- http://www.webmin.com/index.html
- http://users.telenet.be/MySQLplaylist/pi-hole.pdf
- http://www.instructables.com/id/Adding-Webmin-to-manage-a-Raspberry-Pi/
- http://www.ramoonus.nl/2016/07/16/install-webmin-raspberry-pi-updated/

**Comment by Nvanderbeek** [comment]
Using Webmin good for management and monitoring resources (cpu, memory, disk). Using ubuntu server for my project.

**Comment by teusink** [comment]
For this guide and purpose of the Pi I will not use Webmin. It seems like a cool tool, but it won't be used on this Pi installment, but it increases the attack profile and maintenance burden.
