### ISSUE TITLE
No fail2ban 0.10 release on Pi leads to no protection on IPv6

### ISSUE THREAD

**Issue by teusink** [teusink/Home-Security-by-Pi#26]
No fail2ban 0.10 release on Pi leads to no protection on IPv6

Current release is 0.9.6-2: https://packages.debian.org/stretch/fail2ban

Sources:
- https://unix.stackexchange.com/questions/216689/blocking-ssh-brute-force-attacks-on-ipv6
- https://www.ctrl.blog/entry/fail2ban-ipv6
- http://ncomputers.org/fail2ban

**Comment by teusink** [comment]
So, IPv6 is only allowed from the internal network. On the firewall there should be no IPv6 routing to your Pi present!

**Comment by teusink** [comment]
Still on release 0.9.6.

**Comment by teusink** [comment]
Merged with: https://github.com/teusink/Home-Security-by-Pi/issues/12

**Comment by SuperSandro2000** [comment]
Yeah, Debians stupid system
