### ISSUE TITLE
Look into preventing DNS reflection attack

### ISSUE THREAD

**Issue by teusink** [teusink/Home-Security-by-Pi#3]
Look into preventing DNS reflection attack

Sources:
- https://github.com/pi-hole/pi-hole/issues/683#issuecomment-246776571

**Comment by teusink** [comment]
DNS reflection attack is not much of an issue when shielded from the outside world. So won;t look further into this. BUT, iptables can help improve security of the Pi and, when it happens on the internal network, helps limiting this type of attack.

Nessus also gave a IP-forwarder vulnerability, so I'll also look into blocking the forwarding of IPs if possible (would be sad to break the Pi :)

**Comment by devicenull** [comment]
I'd suggest you reconsider doing nothing here.  It seems like a number of users are installing this on random VPS instances, which leads to the DNS server being exposed to the internet, and being abused to conduct reflection attacks.

At the very least, dropping DNS ANY queries will reduce the ability of this to be abused a little bit, while not effecting any legitimate traffic.

dnsmasq doesn't have a built in way to do this, but it can be accomplished with an iptables rule pretty easily:

<pre>
-A INPUT -p udp --dport 53 -m string --from 50 --algo bm --hex-string "|0000FF0001|" -j DROP
</pre>

**Comment by teusink** [comment]
Hi @devicenull , Thanks for your comment! I will look into your suggestion and see to it that it is added to the guide.

Question, does not the same apply to port 5353 (multi-cast DNS) and 853 (DNS-over-TLS)?

**Comment by devicenull** [comment]
Are you doing anything with mDNS now?  That's generally only used for device discovery within a LAN, and really isn't something that should be exposed via the internet.

DNS via TLS happens via TCP, which is not vulnerable to these spoofing/reflection attacks.

**Comment by teusink** [comment]
Hi, I added some rules to mitigate ddos/amplification attacks. Again, thanks for your suggestion.

I do nothing with mDNS indeed. I checked the iptables, but it isn't opened up anywhere. Or am I missing something? :)
