### ISSUE TITLE
Add support for private DNS with DNS-over-TLS (port 853)

### ISSUE THREAD

**Issue by teusink** [teusink/Home-Security-by-Pi#4]
**Add support for private DNS with DNS-over-TLS (port 853)**

Sources:
- https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Daemon+-+Stubby
- https://github.com/getdnsapi/stubby
- https://blog.sandchaschte.ch/en/pi-hole-with-dns-over-tls
- https://www.reddit.com/r/pihole/comments/78pr6s/google_dns_on_tls_for_android/
- https://medium.com/@alexander_band/privacy-using-dns-over-tls-with-the-new-quad9-dns-service-1ff2d2b687c5
- https://news.ycombinator.com/item?id=15712744

Feature request (won't happen though):
- https://discourse.pi-hole.net/t/implement-dns-over-tls-capability-in-pi-hole/8722

Pros over DNS-over-HTTPS:
- Official standard
- Can choose for Quad9 and its malicious domain blocking

Cons over DNS-over-HTTPS:
- Code still in alpha/beta stage
- No real support

DNS-over-HTTPS ticket: https://github.com/teusink/Home-Security-by-Pi/issues/37

**Comment by jedisct1** [comment]
Official documentation for the client: https://github.com/jedisct1/dnscrypt-proxy/wiki

**Comment by teusink** [comment]
Thanks!

**Comment by teusink** [comment]
Dropped DNSCrypt. It has weaknesses, no official RFC and no support with Cloudflare and Quad9.

**Comment by teusink** [comment]
Might look into this guide from Scott: https://scotthelme.co.uk/securing-dns-across-all-of-my-devices-with-pihole-dns-over-https-1-1-1-1/

**Comment by teusink** [comment]
Waiting for "Duster" release of Debian which will include Stubby for DoT. Then perhaps the rest of this guide can be incorporated: https://blog.sandchaschte.ch/en/pi-hole-with-dns-over-tls

I do not want to compile myself, but work with packages due to making updates more easy to automate.

**Comment by teusink** [comment]
Repo will be archived, so this issue won't receive a follow up.
