### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by Warmax356** [teusink/Home-Security-by-Pi#44]
please note all links on the main page are not working most no longer exist or service is suspended.

i am talking about this: https://github.com/teusink/Home-Security-by-Pi/blob/master/2-appendix-PiHole-blocklists.md as this is what google highlights for this project when searching online for pi block lists for malware, phishing etc...

**Comment by teusink** [comment]
Hi @Warmax356, I clicked through some sources, but these are indeed not working anymore. As I no longer maintain this repo (its archived) I won't update the links anymore. I am not using a Pi-Hole myself anymore.

My suggestion would be searching the Pi-Hole forum at https://discourse.pi-hole.net/ . I hope this helps. Cheers.
